#define ZOOM 1
#define DIVIDETIME 5
#define WINDOW_SCALE 10
#define SHOOT_COOLDOWN 24
#define SEGMENTSCERCLES 64
#define BULLETSPEED 2
#define BULLETDAMAGES 10
#define X 0
#define Y 1
#define ACC 0.027
#define MOMENTUM 0.85